

services:
  cowrie:
    image: cowrie/cowrie
    container_name: cowrie
    restart: always
    ports:
      - "2223:2222"
    volumes:
      - cowrie_logs:/cowrie/var/lib/cowrie/log
    networks:
      - honeypot_net

networks:
  honeypot_net:
    driver: bridge

volumes:
  cowrie_logs: