services:
  cowrie:
    image: cowrie/cowrie
    container_name: cowrie
    restart: always
    ports:
      - "2223:2222"
    volumes:
      - cowrie_logs:/cowrie/var/lib/cowrie/log
    networks:
      - honeypot_net

  ftpot:
    build: ./honeypots/ftp
    container_name: ftpot
    restart: always
    ports:
      - "2121:21"
    volumes:
      - ftp_logs:/logs
    networks:
      - honeypot_net

  httppot:
    build: ./honeypots/http
    container_name: httppot
    restart: always
    ports:
      - "8080:80"
    volumes:
      - http_logs:/logs
    networks:
      - honeypot_net

  collector:
    build: ./collector
    container_name: collector
    restart: always
    volumes:
      - http_logs:/logs/http
      - ftp_logs:/logs/ftp
      - collected_logs:/collected
    networks:
      - honeypot_net
    depends_on:
      - ftpot
      - httppot

  enrichment:
    build: ./enrichment
    container_name: enrichment
    restart: always
    env_file:
      - .env
    volumes:
      - collected_logs:/collected
      - enriched_logs:/enriched
    networks:
      - honeypot_net
    depends_on:
      - collector

networks:
  honeypot_net:
    driver: bridge

volumes:
  cowrie_logs:
  ftp_logs:
  http_logs:
  collected_logs:
  enriched_logs: