services:
  cowrie:
    image: cowrie/cowrie
    container_name: cowrie
    restart: always
    ports:
      - "2223:2222"
    volumes:
      - cowrie_logs:/cowrie/var/lib/cowrie/log
    networks:
      - honeypot_net

  ftpot:
    build: ./honeypots/ftp
    container_name: ftpot
    restart: always
    ports:
      - "2121:21"
    volumes:
      - ftp_logs:/logs
    networks:
      - honeypot_net

  httppot:
    build: ./honeypots/http
    container_name: httppot
    restart: always
    ports:
      - "8080:80"
    volumes:
      - http_logs:/logs
    networks:
      - honeypot_net

networks:
  honeypot_net:
    driver: bridge

volumes:
  cowrie_logs:
  ftp_logs:
  http_logs: